# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHR0MoVdeSWTOBvNp5SV-dCVt0veVfVR
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app11.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import joblib
# 
# model=joblib.load('model.h5')
# scaler=joblib.load('scaler.h5')
#

! pip install streamlit

ParentMaritalStatus = {
    'widowed': [0, 0, 1],
    'married': [1, 0, 0],
    'single': [0, 1, 0],
    'divorced': [0, 0, 0]
}

PracticeSport = {
    'regularly': [1, 0],
    'sometimes': [0, 1],
    'never': [0, 0],
}


EthnicGroup = {
    'group A': [0, 0, 0, 0],
    'group B': [1, 0, 0, 0],
    'group C': [0, 1, 0, 0],
    'group D': [0, 0, 1, 0],
    'group E': [0, 0, 0, 1],
}

ParentEduc = {
    'bachelors degree': [1, 0, 0, 0, 0],
    'some college': [0, 0, 0, 1, 0],
    'masters degree': [0, 0, 1, 0, 0],
    'associates degree': [0, 0, 0, 0, 0],
    'high school': [0, 1, 0, 0, 0],
    'some high school': [0, 0, 0, 0, 1],
}

WklyStudyHours = {
    '< 5': [1, 0],
    '> 10': [0, 1],
    '5 - 10': [0, 0],
}
Gender = {
    'male': [1],
    'female': [0],

}

IsFirstChild_yes = {
    'yes': [1],
    'no': [0],

}
testprep = {
    'yes': [0],
    'none': [1],
}
LunchType = {
    'free/reduced': [0],
    'standard': [1],
}

st.title('Math Test scores predicting app')
st.info(' tryin to build a model on the School dataset')

ReadingScore=st.number_input('Enter Reading Score: ')
WritingScore=st.number_input('Enter Writing Score: ')
#NrSiblings = st.slider('siblings? ',0,7)
PracticeSport_selection=st.selectbox('PracticeSport? ',['regularly','sometimes','never'])
PS=PracticeSport[PracticeSport_selection]
ParentMaritalStatus_selection=st.selectbox('ParentMaritalStatus? ',['widowed','married','single', 'divorced'])
PMS=ParentMaritalStatus[ParentMaritalStatus_selection]
WklyStudyHours_selection=st.selectbox('WklyStudyHours? ',['< 5','> 10','5 - 10'])
WSH=WklyStudyHours[WklyStudyHours_selection]
EthnicGroup_selection=st.selectbox('EthnicGroup? ',['group A','group B','group C', 'group D', 'group E'])
EG=EthnicGroup[EthnicGroup_selection]
ParentEduc_selection=st.selectbox('ParentEduc? ',['bachelors degree','some college','masters degree', 'associates degree', 'high school', 'some high school'])
PE=ParentEduc[ParentEduc_selection]
Gender_selection=st.selectbox('Gender? ',['female','male'])
g=Gender[Gender_selection]
testprep_selection=st.selectbox('testprep taken? ',['yes','none'])
tp=testprep[testprep_selection]
IsFirstChild_yes_selection=st.selectbox('IsFirstChild? ',['yes','no'])
fc=IsFirstChild_yes[IsFirstChild_yes_selection]
LunchType_selection=st.selectbox('LunchType? ',['standard','free/reduced'])
lt=LunchType[LunchType_selection]

data=[ReadingScore,WritingScore]+g+EG+PE+lt+tp+PS+WSH

data_scaled=scaler.transform([data])

result=model.predict(data_scaled)

st.write(result)

!npm install localtunnel

!streamlit run app11.py &>/content/logs.txt &

!npx localtunnel --port 8501 & curl ipv4.icanhazip.com

